apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: plaintextdemo-nodejs
build:
  artifacts:
  - image: hellonode
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
