apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-deploy
  labels:
    app: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node-container
        image: hellonode:v1
      #   volumeMounts:
      #   - name: greeting-config
      #     mountPath: /etc/config
      # volumes:
      # - name: greeting-config
      #   secret:
      #     secretName: greetingconfig
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc
  labels:
    app: hello-node
spec:
  type: NodePort
  ports:
  - port: 31234
    nodePort: 30123
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hello-node
